version: '2'
services:
    iconlab-app:
        image: iconlab
        external_links:
            - iconlab-postgresql:postgresql
            - iconlab-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/iconlab
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    iconlab-postgresql:
        extends:
            file: postgresql.yml
            service: iconlab-postgresql
    iconlab-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: iconlab-elasticsearch
